  # .github/workflows/buf-push.yaml
  name: Push to BSR

  on:
    push:
      branches:
        - main # Or your default branch

  jobs:
    push-to-bsr:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4

        - name: Setup Buf
          uses: bufbuild/buf-setup-action@v1
          with:
            version: 'latest'

        - name: Push to BSR
          uses: bufbuild/buf-push-action@v1
          with:
            buf_token: ${{ secrets.BUF_TOKEN }}
            input: proto # The directory containing your buf.yaml and proto files